# Generated by Django 2.1.4 on 2018-12-21 06:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locallibrary', '0003_auto_20181221_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_view_borrowed', 'view_borrowed'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('ae745e61-5813-496f-bd9e-827d850c9d0c'), primary_key=True, serialize=False),
        ),
    ]
