# Generated by Django 2.1.4 on 2018-12-21 07:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locallibrary', '0004_auto_20181221_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_view_borrowed', 'Can View Books Borrowed'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('1d73f28b-f756-4438-8c6b-7fbf1cf42198'), primary_key=True, serialize=False),
        ),
    ]
