# Generated by Django 2.1.4 on 2018-12-21 07:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locallibrary', '0005_auto_20181221_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('Can View Borrowed', 'View Books Borrowed'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('cbd2542d-89fb-4a74-b122-f201c5c1ee87'), primary_key=True, serialize=False),
        ),
    ]
