# Generated by Django 2.1.4 on 2018-12-21 07:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locallibrary', '0006_auto_20181221_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('Can_View_Borrowed', 'View Books Borrowed'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('058c0881-fd06-4764-a086-c9bc22188454'), primary_key=True, serialize=False),
        ),
    ]
