# Generated by Django 2.1.4 on 2018-12-21 07:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('locallibrary', '0007_auto_20181221_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('CanViewBorrowed', 'View Books Borrowed'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('870fc5ed-4742-45d3-90b8-490905e77994'), primary_key=True, serialize=False),
        ),
    ]
